# Generated by Django 4.1.7 on 2023-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
