# Generated by Django 4.1.7 on 2023-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_bien_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bienes/'),
        ),
    ]
