# Generated by Django 4.1.7 on 2023-04-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_comentario_delete_comentar_delete_compra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Mensaje',
        ),
    ]
